/**
 * Next Up Games API
 * API de proyecto final Desarrollo de Aplicaciones Web.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Genero } from './genero';
import { Juego } from './juego';


export interface JuegosGenero { 
    idJuego?: Juego;
    idGenero?: Genero;
}
