/**
 * Next Up Games API
 * API de proyecto final Desarrollo de Aplicaciones Web.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Genero } from '../model/genero';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GeneroService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Crear genero
     * 
     * @param body Objecto genero creado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createGenre(body: Genero, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public createGenre(body: Genero, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public createGenre(body: Genero, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public createGenre(body: Genero, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createGenre.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/genero/create`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Borrar genero
     * 
     * @param idGenero El id del genero que tiene que ser eliminado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteGenre(idGenero: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteGenre(idGenero: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteGenre(idGenero: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteGenre(idGenero: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idGenero === null || idGenero === undefined) {
            throw new Error('Required parameter idGenero was null or undefined when calling deleteGenre.');
        }

        let headers = this.defaultHeaders;
        if (idGenero !== undefined && idGenero !== null) {
            headers = headers.set('idGenero', String(idGenero));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/genero/delete`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Recibir todos los generos
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllGenres(observe?: 'body', reportProgress?: boolean): Observable<Array<Genero>>;
    public getAllGenres(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Genero>>>;
    public getAllGenres(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Genero>>>;
    public getAllGenres(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Genero>>(`${this.basePath}/genero/getAll`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Actualizar genero
     * 
     * @param idGenero id del genero que tiene que ser actualizado
     * @param body Objeto genero actualizado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateGenre(idGenero: string, body: Genero, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateGenre(idGenero: string, body: Genero, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateGenre(idGenero: string, body: Genero, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateGenre(idGenero: string, body: Genero, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idGenero === null || idGenero === undefined) {
            throw new Error('Required parameter idGenero was null or undefined when calling updateGenre.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateGenre.');
        }

        let headers = this.defaultHeaders;
        if (idGenero !== undefined && idGenero !== null) {
            headers = headers.set('idGenero', String(idGenero));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/genero/update`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
