/**
 * Next Up Games API
 * API de proyecto final Desarrollo de Aplicaciones Web.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Interes } from '../model/interes';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class InteresService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Crear interes
     * 
     * @param body Objecto interes creado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createInterest(body: Interes, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public createInterest(body: Interes, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public createInterest(body: Interes, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public createInterest(body: Interes, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createInterest.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/interes/create`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Borrar interes
     * 
     * @param idUsuario El id del usuario del interes que tiene que ser eliminado
     * @param idJuego El id del juego del interes que tiene que ser eliminado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteInterest(idUsuario: number, idJuego: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteInterest(idUsuario: number, idJuego: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteInterest(idUsuario: number, idJuego: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteInterest(idUsuario: number, idJuego: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idUsuario === null || idUsuario === undefined) {
            throw new Error('Required parameter idUsuario was null or undefined when calling deleteInterest.');
        }

        if (idJuego === null || idJuego === undefined) {
            throw new Error('Required parameter idJuego was null or undefined when calling deleteInterest.');
        }

        let headers = this.defaultHeaders;
        if (idUsuario !== undefined && idUsuario !== null) {
            headers = headers.set('idUsuario', String(idUsuario));
        }
        if (idJuego !== undefined && idJuego !== null) {
            headers = headers.set('idJuego', String(idJuego));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/interes/delete`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Recibir todos los intereses
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllInterests(observe?: 'body', reportProgress?: boolean): Observable<Array<Interes>>;
    public getAllInterests(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Interes>>>;
    public getAllInterests(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Interes>>>;
    public getAllInterests(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Interes>>(`${this.basePath}/interes/getAll`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Actualizar interes
     * 
     * @param idUsuario id del usuario del interes que tiene que ser actualizado
     * @param idJuego id del juego del interes que tiene que ser actualizado
     * @param body Objeto interes actualizado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateInterest(idUsuario: number, idJuego: number, body: Interes, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateInterest(idUsuario: number, idJuego: number, body: Interes, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateInterest(idUsuario: number, idJuego: number, body: Interes, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateInterest(idUsuario: number, idJuego: number, body: Interes, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idUsuario === null || idUsuario === undefined) {
            throw new Error('Required parameter idUsuario was null or undefined when calling updateInterest.');
        }

        if (idJuego === null || idJuego === undefined) {
            throw new Error('Required parameter idJuego was null or undefined when calling updateInterest.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateInterest.');
        }

        let headers = this.defaultHeaders;
        if (idUsuario !== undefined && idUsuario !== null) {
            headers = headers.set('idUsuario', String(idUsuario));
        }
        if (idJuego !== undefined && idJuego !== null) {
            headers = headers.set('idJuego', String(idJuego));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/interes/getAllById`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
