/**
 * Next Up Games API
 * API de proyecto final Desarrollo de Aplicaciones Web.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { JuegosPlataforma } from '../model/juegosPlataforma';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class JuegosPlataformaService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Crear juegos_plataforma
     * 
     * @param body Objecto juegos_plataforma creado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createGamePlatform(body: JuegosPlataforma, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public createGamePlatform(body: JuegosPlataforma, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public createGamePlatform(body: JuegosPlataforma, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public createGamePlatform(body: JuegosPlataforma, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createGamePlatform.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/juegos_plataforma/create`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Borrar juegos_plataforma
     * 
     * @param idJuego id del juego del juegos_plataforma que tiene que ser eliminado
     * @param idPlataforma id del genero del juegos_plataforma que tiene que ser eliminado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteGamePlatform(idJuego: number, idPlataforma: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteGamePlatform(idJuego: number, idPlataforma: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteGamePlatform(idJuego: number, idPlataforma: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteGamePlatform(idJuego: number, idPlataforma: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idJuego === null || idJuego === undefined) {
            throw new Error('Required parameter idJuego was null or undefined when calling deleteGamePlatform.');
        }

        if (idPlataforma === null || idPlataforma === undefined) {
            throw new Error('Required parameter idPlataforma was null or undefined when calling deleteGamePlatform.');
        }

        let headers = this.defaultHeaders;
        if (idJuego !== undefined && idJuego !== null) {
            headers = headers.set('idJuego', String(idJuego));
        }
        if (idPlataforma !== undefined && idPlataforma !== null) {
            headers = headers.set('idPlataforma', String(idPlataforma));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/juegos_plataforma/delete`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Recibir todos los juegos de una plataforma por id
     * 
     * @param idPlataforma El id de la plataforma del que se quiere recibir juegos.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllGameByPlatformId(idPlataforma: string, observe?: 'body', reportProgress?: boolean): Observable<JuegosPlataforma>;
    public getAllGameByPlatformId(idPlataforma: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<JuegosPlataforma>>;
    public getAllGameByPlatformId(idPlataforma: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<JuegosPlataforma>>;
    public getAllGameByPlatformId(idPlataforma: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlataforma === null || idPlataforma === undefined) {
            throw new Error('Required parameter idPlataforma was null or undefined when calling getAllGameByPlatformId.');
        }

        let headers = this.defaultHeaders;
        if (idPlataforma !== undefined && idPlataforma !== null) {
            headers = headers.set('idPlataforma', String(idPlataforma));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<JuegosPlataforma>(`${this.basePath}/juegos_plataforma/getAllGameByPlatformId`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Recibir todos los valores de juegos_plataforma
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllGamePlatforms(observe?: 'body', reportProgress?: boolean): Observable<Array<JuegosPlataforma>>;
    public getAllGamePlatforms(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<JuegosPlataforma>>>;
    public getAllGamePlatforms(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<JuegosPlataforma>>>;
    public getAllGamePlatforms(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<JuegosPlataforma>>(`${this.basePath}/juegos_plataforma/getAll`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Recibir todas las plataformas de un juego por id
     * 
     * @param idJuego El id del juego del que se quiere recibir sus plataformas.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPlatformByGameId(idJuego: number, observe?: 'body', reportProgress?: boolean): Observable<JuegosPlataforma>;
    public getAllPlatformByGameId(idJuego: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<JuegosPlataforma>>;
    public getAllPlatformByGameId(idJuego: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<JuegosPlataforma>>;
    public getAllPlatformByGameId(idJuego: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idJuego === null || idJuego === undefined) {
            throw new Error('Required parameter idJuego was null or undefined when calling getAllPlatformByGameId.');
        }

        let headers = this.defaultHeaders;
        if (idJuego !== undefined && idJuego !== null) {
            headers = headers.set('idJuego', String(idJuego));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<JuegosPlataforma>(`${this.basePath}/juegos_plataforma/getAllPlatformByGameId`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Actualizar juegos_plataforma
     * 
     * @param idJuego id del juego del juegos_plataforma que tiene que ser actualizado
     * @param idPlataforma id de la plataforma del juegos_plataforma que tiene que ser actualizado
     * @param body Objeto juegos_plataforma actualizado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateGamePlatform(idJuego: number, idPlataforma: string, body: JuegosPlataforma, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateGamePlatform(idJuego: number, idPlataforma: string, body: JuegosPlataforma, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateGamePlatform(idJuego: number, idPlataforma: string, body: JuegosPlataforma, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateGamePlatform(idJuego: number, idPlataforma: string, body: JuegosPlataforma, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idJuego === null || idJuego === undefined) {
            throw new Error('Required parameter idJuego was null or undefined when calling updateGamePlatform.');
        }

        if (idPlataforma === null || idPlataforma === undefined) {
            throw new Error('Required parameter idPlataforma was null or undefined when calling updateGamePlatform.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateGamePlatform.');
        }

        let headers = this.defaultHeaders;
        if (idJuego !== undefined && idJuego !== null) {
            headers = headers.set('idJuego', String(idJuego));
        }
        if (idPlataforma !== undefined && idPlataforma !== null) {
            headers = headers.set('idPlataforma', String(idPlataforma));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/juegos_plataforma/update`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
