/**
 * Next Up Games API
 * API de proyecto final Desarrollo de Aplicaciones Web.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Plataforma } from '../model/plataforma';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PlataformaService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Crear plataforma
     * 
     * @param body Objecto plataforma creado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPlatform(body: Plataforma, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public createPlatform(body: Plataforma, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public createPlatform(body: Plataforma, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public createPlatform(body: Plataforma, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createPlatform.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/plataforma/create`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Borrar plataforma
     * 
     * @param idPlataforma El id de la plataforma que tiene que ser eliminada
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePlatform(idPlataforma: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deletePlatform(idPlataforma: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deletePlatform(idPlataforma: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deletePlatform(idPlataforma: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlataforma === null || idPlataforma === undefined) {
            throw new Error('Required parameter idPlataforma was null or undefined when calling deletePlatform.');
        }

        let headers = this.defaultHeaders;
        if (idPlataforma !== undefined && idPlataforma !== null) {
            headers = headers.set('idPlataforma', String(idPlataforma));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/plataforma/delete`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Recibir todas las plataformas
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPlatforms(observe?: 'body', reportProgress?: boolean): Observable<Array<Plataforma>>;
    public getAllPlatforms(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Plataforma>>>;
    public getAllPlatforms(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Plataforma>>>;
    public getAllPlatforms(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Plataforma>>(`${this.basePath}/plataforma/getAll`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Actualizar usuario
     * 
     * @param idPlataforma id de la plataforma que tiene que ser actualizada
     * @param body Objeto plataforma actualizado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePlatform(idPlataforma: string, body: Plataforma, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updatePlatform(idPlataforma: string, body: Plataforma, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updatePlatform(idPlataforma: string, body: Plataforma, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updatePlatform(idPlataforma: string, body: Plataforma, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlataforma === null || idPlataforma === undefined) {
            throw new Error('Required parameter idPlataforma was null or undefined when calling updatePlatform.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updatePlatform.');
        }

        let headers = this.defaultHeaders;
        if (idPlataforma !== undefined && idPlataforma !== null) {
            headers = headers.set('idPlataforma', String(idPlataforma));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/plataforma/update`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
